# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Georgie
email: george.taveras1231@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Where I share my learnings in software and web development
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://GeorgeTaveras1231.github.io" # the base hostname & protocol for your site
twitter_username: glt123190
github_username:  GeorgeTaveras1231
old_blog_url: "http://georgielovesoup.tumblr.com/"

# Build settings
markdown: kramdown
exclude:
  - Gemfile*
  - docker-compose.yml
  - scripts/
  - old/
